### ISSUE TITLE
Think about multi-platform serial comm solutions

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/yarp-devices#13]
From bottom of https://ubuntuforums.org/archive/index.php/t-896869.html (mujambee):
```
Under Unix, a serial port is a virtual file, names start at /dev/ttys0 and count up. Under Windows is the same, but names start at COM1, so to open a serial port you should use to fopen( "/dev/tty0", "r" ) under ux and fopen( "COM1", "r" ) under win. Unfortunately fopen cant open COM ports in recent versions of Windows.

Not sure how it works with streams, so you may be able to use C++ streams, you just need to conditionaly compile device names; something like:


#include <iostream>
#include <fstream>

#ifdef WINDOWS
const char pnames[][12]={ "COM1", "COM2", "COM3", "COM4" };
#else
const char pnames[][12]={ "/dev/ttys0", "/dev/ttys1", "/dev/ttys2", "/dev/ttys3" };
#endif
...
...
...

std::ifstream ifs( pnames[port_number] );


Anyway, if you are just learning C, it could be a good exercise to create wrapper functions and conditionaly include calls to fopen, fread, fclose in your unix version and OpenFile, ReadFile and CloseHandle in your Windows version.
```

**Comment by PeterBowman** [comment]
Isn't that plain-C approach heavily Linux-specific? I mean, check all those `read`, `write` and `open` calls [in this file](https://sourceforge.net/p/asrob/svn/HEAD/tree/OLD/ecro/software/netbook/src/libraries/AsrobPlugins/skymegabot/HelperFuncs.cpp) (plus termios.h and so on). I've never bothered to learn IO on Windows, perhaps it's not that hard to adopt the *C standard* way - or just wrap platform-specific lines in their corresponding `#ifdef`s: https://stackoverflow.com/a/13198670. Alternatively, we could manage serial comms with ACE, which is indeed multi-platform as already implemented in [YARP's `serialport` device](https://github.com/robotology/yarp/tree/e1d7a45621ea97a76136f94511a3b4c956506bf5/src/devices/serialport).

**Comment by jgvictores** [comment]
Oh, ok! 

Thanks for all this info. I guess https://github.com/asrob-uc3m/yarp-devices/issues/21 is the priority now, but it's great to have some pointers towards a multiplatform solution.

Within the 3 options presented (ACE, yarp device that uses ACE, preprocessor), I have no clear preferences.

**Comment by PeterBowman** [comment]
It turns out libserial is not stale, the `libserial-dev` package has been upgraded from 0.6 to 1.0 between Ubuntu bionic and focal ([ref](https://packages.ubuntu.com/focal/libserial-dev)). These versions are not compatible. I'd strongly advise moving towards YARP's `serialport` device, as suggested earlier.

**Comment by PeterBowman** [comment]
> I'd strongly advise moving towards YARP's `serialport` device, as suggested earlier.

Done at https://github.com/asrob-uc3m/yarp-devices/commit/e65ada4dca13977f1d4a547aea9f04a2abf99f04. It is necessary to install `libace-dev` via apt, then compile YARP with `-DSKIP_ACE=OFF` (this is the default) and `-DENABLE_yarpmod_serialport=ON`.
