### ISSUE TITLE
LaserTowerOfDeath

### ISSUE THREAD

**Issue by Leytha** [asrob-uc3m/yarp-devices#19]
When trying to move LaserTowerOfDeath the function `tiltDown` is receiving a value which is not using at all. Instead of that, it constantly moves 10 degrees down, and it is not possible to tilt up. 
I think the function `tiltDown` should use the input value to modify `tiltJointValue`.

Current function:

https://github.com/asrob-uc3m/yarp-devices/blob/7db08bd3433396097e43ef8fc3906a62d2387a94/libraries/YarpPlugins/LaserTowerOfDeathController/LaserTowerOfDeathController.cpp#L31-L38

It may be due to this commit:

https://github.com/asrob-uc3m/yarp-devices/commit/ad83d1b6921ace19728688bbc26c63ab8b3c5fff

**Comment by jgvictores** [comment]
ad83d1b was necessary because tha API changed, but yes, due to the API change we should now not completely ignore the incoming `value`: at least the sign of `value` is relevant information and should be taken into account.
