### ISSUE TITLE
CMake find_package for certain devices: libserial, wiringpi...

### ISSUE THREAD

**Issue by jgvictores** [asrob-uc3m/yarp-devices#2]
_From @jgvictores on December 2, 2017 14:33_

Example compilation error:
```
robotDevastation-robots/libraries/YarpPlugins/LaserTowerOfDeathController/LaserTowerOfDeathController.hpp:14:26: fatal error: SerialStream.h: No such file or directory
```

Will happen due to:
- YarpPlugins/LaserTowerOfDeathController/LaserTowerOfDeathController.hpp:#include <SerialStream.h>
- YarpPlugins/EcroWheelController/EcroWheelController.hpp:#include <SerialStream.h>
- YarpPlugins/EcroPwmController/EcroPwmController.hpp:#include <SerialStream.h>

_Copied from original issue: asrob-uc3m/robotDevastation-robots#41_

Edit: see https://github.com/asrob-uc3m/robotDevastation-user-manual/blob/aa35659774f3fb7943918f04167f59a719ed4d0f/en/install-robot-devastation/robots-ubuntu.md

**Comment by PeterBowman** [comment]
Done at https://github.com/asrob-uc3m/yarp-devices/commit/55e101164fbdb2a95012cc7719cd2b1e81e534c3.

**Comment by PeterBowman** [comment]
Follow-up: https://github.com/asrob-uc3m/yarp-devices/issues/15.
