### ISSUE TITLE
Merge IRobotManager moveForward/moveBackwards and similar pairs?

### ISSUE THREAD

**Issue by PeterBowman** [asrob-uc3m/yarp-devices#4]
_From @jgvictores on December 13, 2017 22:5_

Merge [IRobotManager](https://github.com/asrob-uc3m/yarp-devices/blob/3cb54359485954c318eb9f05ede3a1339dde1794/libraries/YarpPlugins/IRobotManager.hpp#L22-L23) `moveForward()`/`moveBackwards()` and similar pairs?

Move, turn, pan, tilt all get (signed) ints as signature. Could be merged to reduce the functions.

PS: I'd go for `double` rather than `int`, and document units (e.g. attempt `m/s` rather than undocumented notion of percentage).

_Copied from original issue: asrob-uc3m/robotDevastation-robots#42_

Affects:
- https://github.com/asrob-uc3m/robotDevastation 
- https://github.com/roboticslab-uc3m/openrave-yarp-plugins ( libraries/YarpPlugins/YarpOpenraveRobotManager )
- https://github.com/jgvictores/2018-ptmr ( examples )

**Comment by jgvictores** [comment]
Updated issue description to cite the affected repositories, added `tracking` label.

**Comment by jgvictores** [comment]
WIP at 44154b43b239a183ac4e58306a16b849838e810c.

**Comment by jgvictores** [comment]
Synced RD at https://github.com/asrob-uc3m/robotDevastation/commit/84fb0ba9bf2f1cbda4bc687457e3e103cc98c2e9

**Comment by jgvictores** [comment]
OR-Y-P at https://github.com/roboticslab-uc3m/openrave-yarp-plugins/commit/36467b5ac6d289d3c3f97d690394a55f688eac35

**Comment by jgvictores** [comment]
Merged into this repository at 341a73c99f794567cf872485c04e159583a0f2f8. Will go to `master` too.

**Comment by jgvictores** [comment]
Synced RD at https://github.com/asrob-uc3m/robotDevastation/commit/ca637d589b5b8fd86264f4295d2d8093f88bf9fe

**Comment by jgvictores** [comment]
Synced OR-Y-P at https://github.com/roboticslab-uc3m/openrave-yarp-plugins/commit/ef2505e5327b4405357a88cc1450278e244bfee8

**Comment by jgvictores** [comment]
Synced 2018-PTMR examples at https://github.com/jgvictores/2018-ptmr/commit/e790ea8debfc48c27c58919cefb78b8a06f0b30b

**Comment by jgvictores** [comment]
All set. Latest API:
- https://github.com/asrob-uc3m/yarp-devices/blob/develop/libraries/YarpPlugins/IRobotManager.hpp ([permalink](https://github.com/asrob-uc3m/yarp-devices/blob/341a73c99f794567cf872485c04e159583a0f2f8/libraries/YarpPlugins/IRobotManager.hpp))
- http://asrob.uc3m.es/dox-yarp-devices/classasrob_1_1RobotClient.html

Will create follow-up issue to document the fact that devices that are not compiled by default are currently broken (`LaserTowerOfDeath`, etc).
